# Configuration parameters for styling Excel Spreadsheets
# (see end of file for Excel color codes)

[site_data_sheet]
sheet_name = "Site data"
name_header = "Site ID"
longitude_header = "Longitude (DD)"
latitude_header = "Latitude (DD)"
action_cost_header = "Cost of “{action_ids}”"
col_width_padding = 10
sub_message_height = 120
main_message_height = 20
main_message = "Please enter information for your sites into this worksheet."
sub_message = "Specifically, we ask that you input the longitude and latitude (in decimal degrees) of each site. If you have a shapefile with spatial locations (e.g. point localities, boundaries) of your sites, these can also be supplied in the NCC Priority Actions App. We also ask that you input the cost of implementing each management action (e.g. in Canadian Dollars) within each site. Please note that cost values should not be below zero (though they can equal zero) and not be greater than 1,000,000 (i.e. one million). As such, you might need to rescale your cost values. For example, if one of your cost values is “10000000” Canadian Dollars, instead of inputting values as Canadian Dollars, you could you input values as thousands of Canadian Dollars (i.e. “10000”). Please take care to ensure that all cost values are in the same units. After filling out this worksheet, every light gray cell should have a numerical value."

[status_data_sheet]
sheet_name = "Status data"
name_header = "Site ID"
action_status_header = "Status of “{action_ids}”"
col_width_padding = 10
sub_message_height = 100
main_message_height = 20
main_message = "Please enter status information for your sites into this worksheet."
sub_message = "Specifically, we ask that you input data indicating which management actions are currently being implemented within each site. By default, none of the actions are currently implemented within each site. To specify that a certain a certain action can be implemented within a certain site, please enter value of “1”. This information, if you prefer, can also be specified within the NCC Priority Actions App---however, you will have to re-specify this information each and every time you open the NCC Priority Actions App."

[feasibility_data_sheet]
sheet_name = "Feasibility data"
name_header = "Site ID"
action_status_header = "Feasibility of “{action_ids}”"
col_width_padding = 10
sub_message_height = 100
main_message_height = 20
main_message = "Please enter feasibility information for your sites into this worksheet."
sub_message = "Specifically, we ask that you input data indicating which management actions are feasible to implement within each site. By default, all actions can be potentially implemented within each and every site. To specify that a certain a certain action cannot be implemented within a certain site, please enter value of “0”. You can also ensure that a certain site can ONLY have a certain action implemented within it, by specifying a value of “0” for every other action. This information, if you prefer, can also be specified within the NCC Priority Actions App---however, you will have to re-specify this information each and every time you open the NCC Priority Actions App."

[feature_data_sheet]
sheet_name = "Feature data"
name_header = "Feature ID"
target_header = "Target threshold amount"
weight_header = "Relative importance (weight)"
col_width_padding = 10
sub_message_height = 250
main_message_height = 20
main_message = "Please enter information for your features into this worksheet."
sub_message = "Specifically, we ask that you input values to specify trade-offs for managing different biodiversity elements (e.g. species, habitat types) within your conservation planning exercise. To help prioritize implementation of specific management actions in specific sites, we require an estimate of the minimum amount of each feature you think is important to achieve across all of the sites (termed “target threshold amount”). For example, you could calculate these target threshold amounts as a percentage of the current amount of each feature (e.g. maybe you want to increase the amount of each feature by 50%)? Alternatively, these values could be guided using population viability analyses, statistical models, or expert elicitation. Please take care to ensure that each target value is in the same units as the expectation data. For example, the value in the cell B2 for this spreadsheet should be in the same unit as the values in the B column for all action expectation worksheets (i.e. worksheets starting with the word “Expectation”). To ensure that the prioritization process explicitly accounts for your objectives (i.e. what YOU think is important), you can also specify the relative importance (weight) of each feature. The default value is 1 such that all features are considered equally important. These values should be between 0 and 100. Greater values indicate greater importance. A weight of exactly 0 means that a feature is not important at all and does not “count” when comparing different conservation plans. Please note that these values can be changed later in the NCC Priority Actions App. After filling out this worksheet, every light gray cell should have a numerical value."

[action_expectation_sheet]
sheet_name = "Expectation of “{action_ids}”"
name_header = "Site ID"
action_expectation_header = "Amount of “{feature_ids}”"
col_width_padding = 10
sub_message_height = 160
main_message_height = 20
main_message = "Please enter information for your “{action_ids}” action into this worksheet."
sub_message = "Specifically, we ask that you input the amount of each biodiversity element (termed feature) that you would expect to occur within each site after you implemented the “{action_ids}” action. For example, these values could indicate that you expect a certain feature (e.g. species) to be present (using a value of “1”) or absent (using a value of “0”) within certain sites after this action is implemented. Alternatively, these could represent quantities such as expected population size (using count values) or amount of habitat (in km^2). Although different feature can have different units, each feature must have values in the same units. Thus all rows in the same column within this worksheet must be in the same units. Additionally, across worksheets for different actions (i.e. those starting with the word “Expectation”), the values in the same column must be in the same units (e.g. all values in the column B in each of these of these action worksheets must have the same units). After filling out this worksheet, every light gray cell should have a numerical value."

[site_results_sheet]
sheet_name = "Site results"
name_header = "Site ID"
action_header = "Priority action"
col_width_padding = 10
sub_message_height = 30
main_message_height = 20
main_message = "Site results from prioritization."
sub_message = "This worksheet contains information on which actions were prioritized for implementation within each site. "

[feature_results_sheet]
sheet_name = "Feature results"
name_header = "Feature ID"
action_amount_header = "Expected amount from “{action_ids}” action"
total_amount_header = "Total expected amount"
col_width_padding = 10
sub_message_height = 30
main_message_height = 20
main_message = "Feature results from prioritization."
sub_message = "This worksheet contains information on the expected amount of each feature given the prioritization."

[summary_results_sheet]
sheet_name = "Summary results"
name_header = "Summary statistic"
value_header = "Value"
cost_statistic_name = "Total cost"
n_action_statistic_name = "Number of sites allocated to “{action_ids}”"
col_width_padding = 10
sub_message_height = 30
main_message_height = 20
main_message = "Feature results from prioritization."
sub_message = "This worksheet contains summary information on the prioritization. Each row contains a different statistic to summarize the prioritization."

[error_sheets]
name_header = "Error"
iis_header = "Error"
main_message = "There is no possible solution because (i) at least one of the targets cannot be met, (ii) an action needed to meet a target has been locked out, or (iii) all of the actions for a given site have been locked out."
sub_message = "No valid solution, see Summary tab."
status_prefix = "Status for the site “{site_ids}” and action “{action_ids}”"
target_prefix = "Target for feature “{feature_ids}”"
budget_prefix = "Budget"
lower_bound_message = "is set to zero"
upper_bound_message = "is set to zero"
budget_message = "is too low given the cheapest possible action costs"
target_message = "is too high"

[main_style]
# see for options https://www.rdocumentation.org/packages/openxlsx/versions/4.2.3/topics/createStyle
fontName = "Times New Roman"
fontSize = 16
fontColour = "black"
numFmt = "TEXT"
bgFill = "white"
fgFill = "white"
halign = "center"
valign = "center"
textDecoration = "bold"
locked = true
wrapText = true
border = "TopBottomLeftRight"
borderStyle = "none"

[sub_style]
# see for options https://www.rdocumentation.org/packages/openxlsx/versions/4.2.3/topics/createStyle
fontName = "Times New Roman"
fontSize = 12
fontColour = "black"
numFmt = "TEXT"
bgFill = "white"
fgFill = "white"
halign = "left"
valign = "center"
locked = true
wrapText = true
border = "TopBottomLeftRight"
borderStyle = "none"

[header_style]
# see for options https://www.rdocumentation.org/packages/openxlsx/versions/4.2.3/topics/createStyle
fontName = "Times New Roman"
fontSize = 14
fontColour = "#283b39"
numFmt = "TEXT"
bgFill = "#7b9d7a"
fgFill = "#7b9d7a"
halign = "center"
valign = "center"
textDecoration = "bold"
borderColour = "#283b39"
borderStyle = "thin"
border = "TopBottomLeftRight"
locked = true

[label_style]
# see for options https://www.rdocumentation.org/packages/openxlsx/versions/4.2.3/topics/createStyle
fontName = "Times New Roman"
fontSize = 12
fontColour = "#283b39"
numFmt = "TEXT"
fgFill = "#7b9d7a"
bgFill = "#7b9d7a"
halign = "center"
valign = "center"
borderColour = "#283b39"
borderStyle = "thin"
border = "TopBottomLeftRight"
locked = true

[data_style]
# see for options https://www.rdocumentation.org/packages/openxlsx/versions/4.2.3/topics/createStyle
fontName = "Arial"
fontSize = 12
fontColour = "#283b39"
numFmt = "NUMBER"
fgFill = "#e3dcd7"
bgFill = "#e3dcd7"
halign = "center"
valign = "center"
locked = false
borderColour = "#283b39"
borderStyle = "thin"
border = "TopBottomLeftRight"

[true_style]
# see for options https://www.rdocumentation.org/packages/openxlsx/versions/4.2.3/topics/createStyle
fontName = "Arial"
fontSize = 12
fontColour = "#115d2f"
numFmt = "0"
bgFill = "#4cbc89"
fgFill = "#4cbc89"
halign = "center"
valign = "center"
locked = false
borderColour = "black"
borderStyle = "thin"
border = "TopBottomLeftRight"

[false_style]
# see for options https://www.rdocumentation.org/packages/openxlsx/versions/4.2.3/topics/createStyle
fontName = "Arial"
fontSize = 12
fontColour = "#b12f31"
numFmt = "0"
bgFill = "#f96e67"
fgFill = "#f96e67"
halign = "center"
valign = "center"
locked = false
borderColour = "black"
borderStyle = "thin"
border = "TopBottomLeftRight"
